name: Flet APK Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Flutter sürümünü boş bırakıyoruz ki Flet en güncelini kendi kursun
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet
        run: |
          python3 -m pip install flet

      - name: Build APK
        run: |
          # --yes komutu ile "yükleyeyim mi?" sorularına otomatik 'evet' diyoruz
          flet build apk --yes --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: otoyikama-app-apk
          path: build/apk/*.apk
