name: Flet APK Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

      - name: Install Flet and Dependencies
        run: |
          python3 -m pip install flet

      - name: Build APK
        run: |
          # Flet build komutunu daha detaylı çalıştırıyoruz
          flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: otoyikama-app-apk
          path: build/apk/*.apk
